### ISSUE TITLE
Update read the docs!

### ISSUE THREAD

**Issue by PennyWieser** [TDGerve/silicH2O#3]
Hi, you might want to update read the docs now its published!
![image](https://github.com/TDGerve/silicH2O/assets/65668673/66a36065-4fda-42b3-94e7-9d37a7c29a51)

**Comment by PennyWieser** [comment]
The structure in read the docs isnt preserved after downloading from github (nor seems to match on github)
![image](https://github.com/TDGerve/silicH2O/assets/65668673/a80ffb51-606e-445c-94d5-37e10eb76243)
![image](https://github.com/TDGerve/silicH2O/assets/65668673/a0874eb7-06dd-4e81-ae02-ed1b35891728)

I also cant find the file mentioned in the docs, nor see the folder silicH2O
![image](https://github.com/TDGerve/silicH2O/assets/65668673/570725c2-2bdd-410f-b353-4d7037e44627)
![image](https://github.com/TDGerve/silicH2O/assets/65668673/af39838a-0c6e-46eb-a331-c45a4af2fc6e)

**Comment by TDGerve** [comment]
Hi Penny,

Thanks for noticing the out of date docs, I'll update those! For the file structure, did you make sure to download the compiled release [from here](https://github.com/TDGerve/silicH2O/releases/tag/v1.0.0), or did you download the whole repo? The release has the file structure mentioned in the docs and includes an executable file. I you want you can also run silicH2O from python, in that case you can clone the repo and run run_silicH2O.py Let me know if you still have any issues!
